### ISSUE TITLE
Issues with the docx/odt paper templates

### ISSUE THREAD

**Issue by moorepants** [moorepants/bmd-templates#25]
I uploaded the bmd2023p.docx into MS Teams then saved it as a PDF from MS Teams (I don't have Word, so maybe this if fraught).

- The "Type of the Paper:" in the title should say "Paper" not "Extended Abstract"
- The latex files has the Author B. One style, but the docx has the Firstname1 A. Lastname11 style. The info in he affiliations parts is also different. Better if we made these match.
- Superscripts on the author names don't show correct in MS Teams or the PDF:
![image](https://github.com/moorepants/bmd-templates/assets/276007/6ce0c6e3-acdf-4e61-8ea5-981bd2836cd0)
- The title wraps after Motorcycle on the docx but after Dynamics on the latex
- Page number of title page is stuck onto the ISSN:
![image](https://github.com/moorepants/bmd-templates/assets/276007/577acad0-2869-4598-b6c6-513ed2e3f56f)
- In first paragraph of introduction we should say they must upload as a docx or odt (PDF not accepted).
- I removed the 600 dpi request in the latex and just changed to 300 dpi for all figures.
- The layout of the figure and table could be made to match the latex order sow that the table is on the third page, this avoids the large whitespace on page 2.
- Vertical spacing in the title is different (smaller) in docx pdf than latex pdf.

**Comment by moorepants** [comment]
odt:

- vertical spacing in pdf of odt is very close (almost perfect) to latex pdf
- same page number issue on first page:
![image](https://github.com/moorepants/bmd-templates/assets/276007/76712455-a76c-4da6-ae90-482251343ba4)

**Comment by moorepants** [comment]
I think the vertical spacing issue is an MS Teams PDF generation issue, as it is not present in the PDF you generated in the webdata folder. In that docx-pdf file there I see this on the last page:
![image](https://github.com/moorepants/bmd-templates/assets/276007/f284ae65-9f1e-4a14-9b45-4689124130ca)

which has the page number on the issn and in the right hand corner.

**Comment by chrismo-schmidt** [comment]
I'm working on the above.

**Comment by chris-konrad** [comment]
I noticed another thing. The captions of the figure are formatted as a table. This seems odd. I just copied it from the abstract template. Should this be a table? And should the figure be in the first row of the table and the caption in the second or is the first row meant to define the margin between figure and table?

**Comment by chris-konrad** [comment]
The "Type of the Paper:" in the title should say "Paper" not "Extended Abstract"
_Corrected in next PR_

The latex files has the Author B. One style, but the docx has the Firstname1 A. Lastname11 style. The info in he affiliations parts is also different. Better if we made these match.
_I propose to use the new format. This should provide better clarity about how to fill in names. What should we keep for affiliations?._

Superscripts on the author names don't show correct in MS Teams or the PDF:
_Corrected in next PR_

The title wraps after Motorcycle on the docx but after Dynamics on the latex
_I am aware of this. However, font size and page width is identical for latex and docx. The difference might be caused by slightly different spacings between letters. In my opinion we can leave it as it is._

Page number of title page is stuck onto the ISSN
_Well spotted! Corrected in next PR_

In first paragraph of introduction we should say they must upload as a docx or odt (PDF not accepted).
_Does Orvium still enable PDF uploads? Anyways, let's add "Please upload your finished manuscript as .odt, .docx. or zipped latex project. PDFs will not be accepted."_

I removed the 600 dpi request in the latex and just changed to 300 dpi for all figures.
_Corrected in next PR_

The layout of the figure and table could be made to match the latex order sow that the table is on the third page, this avoids the large whitespace on page
_Corrected in next PR_

I think the vertical spacing issue is an MS Teams PDF generation issue, as it is not present in the PDF you generated in the webdata folder. In that docx-pdf file there I see this on the last page:
_I checked. In MS Word it looks fine. The page numbers are corrected in next PR_

**Comment by moorepants** [comment]
>  I propose to use the new format. This should provide better clarity about how to fill in names. What should we keep for affiliations?.

How about the FirstName LastName style for the names, but we keep the Dutch and German generic universities.

>  Does Orvium still enable PDF uploads? Anyways, let's add "Please upload your finished manuscript as .odt, .docx. or zipped latex project. PDFs will not be accepted."

I'll also add to latex.

Great on the rest.

**Comment by moorepants** [comment]
Done in #26.

**Comment by moorepants** [comment]
Make these adjustements based on Nicoleta's request too:

- by the name of the journal on any page, instead of The Evolving Scholar (2023), we should have ”The Evolving Scholar Vol. 3, 2023”
- Instead of “paper” ( the type of the paper) we will have on the website “conference paper”
